In [2]:
import torch

In [3]:
tensor_1 = torch.tensor([[1, 2], [1, 3]])
tensor_2 = torch.tensor([[2, 3], [0, 4]])

print(tensor_1 + tensor_2)
print(torch.add(tensor_1, tensor_2))
print(tensor_1.add(tensor_2))


tensor([[3, 5],
        [1, 7]])
tensor([[3, 5],
        [1, 7]])
tensor([[3, 5],
        [1, 7]])


C:\Users\dllab.DLL-047\AppData\Local\Temp\ipykernel_17016\906339351.py:1: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:77.)
  tensor_1 = torch.tensor([[1, 2], [1, 3]])


In [4]:
print(tensor_1 - tensor_2)
print(torch.sub(tensor_1, tensor_2))
print(tensor_1.sub(tensor_2))

tensor([[-1, -1],
        [ 1, -1]])
tensor([[-1, -1],
        [ 1, -1]])
tensor([[-1, -1],
        [ 1, -1]])


In [5]:
print(tensor_1 * tensor_2)
print(torch.mul(tensor_1, tensor_2))
print(tensor_1.mul(tensor_2))

tensor([[ 2,  6],
        [ 0, 12]])
tensor([[ 2,  6],
        [ 0, 12]])
tensor([[ 2,  6],
        [ 0, 12]])


In [6]:
print(tensor_1 / tensor_2)
print(torch.div(tensor_1, tensor_2))
print(tensor_1.div(tensor_2))

tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])
tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])
tensor([[0.5000, 0.6667],
        [   inf, 0.7500]])


In [7]:
print(tensor_1 ** tensor_2)
print(torch.pow(tensor_1, tensor_2))
print(tensor_1.pow(tensor_2))

tensor([[ 1,  8],
        [ 1, 81]])
tensor([[ 1,  8],
        [ 1, 81]])
tensor([[ 1,  8],
        [ 1, 81]])


In [8]:
tensor_1 = torch.tensor([[3, 8], [9, 4]])
tensor_2 = torch.tensor([[2, 3], [5, 4]])

print(tensor_1 % tensor_2)
print(torch.remainder(tensor_1, tensor_2))
print(tensor_1.remainder(tensor_2))

tensor([[1, 2],
        [4, 0]])
tensor([[1, 2],
        [4, 0]])
tensor([[1, 2],
        [4, 0]])


In [ ]:
uninitialized = torch.Tensor(3,2)
rand_initialized = torch.rand(3,2)
matrix_with_ones = torch.ones(3,2)
matrix_with_zeros = torch.zeros(3,2)

In [ ]:
x = torch.ones(3,2)
y = torch.ones(3,2) + 2

In [ ]:
x = torch.rand(2,3,4)
x_with_2n3_dimension = x[1, :, :]
scalar_x = x[1,1,1]     # first value from each dimension

In [ ]:
# numpy like slicing
x = torch.rand(2,3)
print(x[:, 1:])        # skipping first column
print(x[:-1, :])       # skipping last row


In [ ]:
# transpose
x = torch.rand(2,3)
print(x.t())           # size 3x2


In [ ]:
# concatenation and stacking
x = torch.rand(2,3)
concat = torch.cat((x,x))
print(concat)         # Concatenates 2 tensors on zeroth dimension


In [ ]:
x = torch.rand(2,3)
concat = torch.cat((x,x), dim=1)
print(concat)         # Concatenates 2 tensors on first dimension


In [ ]:
x = torch.rand(2,3)
stacked = torch.stack((x,x), dim=0)
print(stacked)        # returns 2x2x3 tensor

In [ ]:
# split: you can use chunk as well
x = torch.rand(2,3)
splitted = x.split(split_size=2, dim=0)
print(splitted)       # 2 tensors of 2x2 and 1x2 size


In [ ]:
#sqeeze and unsqueeze
x = torch.rand(3,2,1) # a tensor of size 3x2x1
squeezed = x.squeeze()
print(squeezed)       # remove the 1 sized dimension


In [ ]:
x = torch.rand(3)
with_fake_dimension = x.unsqueeze(0)
print(with_fake_dimension)        # added a fake zeroth dimension